# mint run xcodegen generate

name: SampleApp
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
  generateEmptyDirectories: true
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 6.0
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.10.2
  ScaryCatScreeningKit:
    path: .
    settings:
      base:
        SWIFT_VERSION: 6.0

schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
    run:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release

  ScaryCatScreeningKitTests:
    build:
      targets:
        ScaryCatScreeningKitTests: test
    test:
      config: Debug
      targets:
        - ScaryCatScreeningKitTests

targets:
  ScaryCatScreeningKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ScaryCatScreenerTests
    dependencies:
      - package: ScaryCatScreeningKit
    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningKitTests
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTED_PLATFORMS: iphonesimulator
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_TESTABILITY: YES
        SWIFT_VERSION: 6.0

  SampleApp:
    type: application
    platform: iOS
    sources:
      - SampleApp
    dependencies:
      - package: ScaryCatScreeningKit
      - package: Kingfisher
    settings:
      base:
        INFOPLIST_FILE: SampleApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningKit.SampleApp
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_TESTABILITY: YES
        SWIFT_VERSION: 6.0
