# mint run xcodegen generate

name: SampleApp
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
  generateEmptyDirectories: true
  createIntermediateGroups: true

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.10.2

schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
    run:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug

targets:
  ScaryCatScreeningKit:
    type: framework
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: Kingfisher
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.ScaryCatScreeningKit

  ScaryCatScreeningKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: ScaryCatScreeningKit
    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningKitTests
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTED_PLATFORMS: iphonesimulator
    resources:
      - Tests/TestResources

  SampleApp:
    type: application
    platform: iOS
    sources:
      - SampleApp
    dependencies:
      - target: ScaryCatScreeningKit
      - package: Kingfisher
    settings:
      base:
        INFOPLIST_FILE: SampleApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningKit.SampleApp
