# mint run xcodegen generate

name: SampleApp
options:
  bundleIdPrefix: com.akitorahayashi.ScaryCatScreeningKit
  deploymentTarget:
    iOS: "13.0"

packages:
  ScaryCatScreeningKit:
    path: .

schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: SampleApp
    dependencies:
      - package: ScaryCatScreeningKit
        product: ScaryCatScreeningKit
    info:
      path: SampleApp/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SampleApp
