name: Cat Screening Kit CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  setup:
    name: Setup Mint
    uses: ./.github/workflows/setup-mint.yml
    permissions:
      contents: read

  code-quality:
    name: Code Quality Check
    needs: setup
    uses: ./.github/workflows/code-quality.yml

  unit-testing:
    name: Unit Testing
    needs: setup
    uses: ./.github/workflows/unit-tests.yml