name: ScaryCatScreeningKit CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # Mintのセットアップ
  setup-mint:
    name: Setup Mint
    uses: ./.github/workflows/setup-mint.yml

  # コード品質チェック
  code-quality:
    name: Code Quality Check
    needs: setup-mint
    uses: ./.github/workflows/code-quality.yml

  # ビルドとテストはビルドが成功してからなぜかテストが実行されずに無限ループに入るのでコメントアウト
  # ローカルで実行する
  # package-test:
  #   name: Run Tests
  #   uses: ./.github/workflows/package-tests.yml
    