name: TieredGridLayout CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality Check
    uses: ./.github/workflows/code-quality.yml