name: TieredGridLayout CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # Mintのセットアップ
  setup-mint:
    name: Setup Mint
    uses: ./.github/workflows/setup-mint.yml

  # Swift Packageのビルドとテスト
  package-test:
    name: Swift Package Test
    uses: ./.github/workflows/package-tests.yml
    secrets: inherit

  # コード品質チェック
  code-quality:
    name: Code Quality Check
    needs: setup-mint
    uses: ./.github/workflows/code-quality.yml

  # ビルドとテスト
  build-and-test:
    name: Run Tests
    needs: setup-mint
    uses: ./.github/workflows/run-tests.yml
    
  # テスト結果レポート生成
  test-report:
    name: Test Report
    needs: [build-and-test, package-test]
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/test-reporter.yml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
    permissions:
      checks: write
      actions: read 
      pull-requests: write
    
  # コードレビュー - PRの場合のみ実行
  code-review:
    name: Code Review
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      contents: read
    uses: ./.github/workflows/copilot-review.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit
    
  # アーカイブビルド検証
  archive-build:
    name: Archive Build
    needs: [setup-mint]
    uses: ./.github/workflows/build-unsigned-archive.yml
    
  # ビルド完了通知
  notify-completion:
    name: Notify Completion
    runs-on: ubuntu-latest
    needs: [code-quality, package-test, build-and-test, test-report, code-review, archive-build]
    if: always()
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Determine Status
        id: status
        run: |
          if [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "icon=✅" >> $GITHUB_OUTPUT
            echo "message=ビルドとテストが成功しました" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "icon=❌" >> $GITHUB_OUTPUT
            echo "message=ビルドまたはテストに失敗しました" >> $GITHUB_OUTPUT
          fi
      
      - name: Add Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `## CI/CD Pipeline Completed ${{ steps.status.outputs.icon }}
              
              ${{ steps.status.outputs.message }}
              
              ### ステータス概要:
              - コード品質チェック: ${{ needs.code-quality.result == 'success' && '✅' || '❌' }}
              - Swift Packageテスト: ${{ needs.package-test.outputs.package_test_result == 'success' && '✅' || (needs.package-test.outputs.package_test_result == 'skipped' && '⏭️' || '❌') }}
              - ビルドとテスト: ${{ needs.build-and-test.result == 'success' && '✅' || '❌' }}
              - テスト結果レポート: ${{ needs.test-report.result == 'success' && '✅' || (needs.test-report.result == 'skipped' && '⏭️' || '❌') }}
              - コードレビュー: ${{ needs.code-review.result == 'success' && '✅' || (needs.code-review.result == 'skipped' && '⏭️' || '❌') }}
              - アーカイブビルド検証: ${{ needs.archive-build.result == 'success' && '✅' || '❌' }}
              `
            }); 