name: Code Quality

on:
  workflow_call:
    outputs:
      result:
        description: "Check Result"
        value: ${{ jobs.format-and-lint.outputs.result }}

jobs:
  format-and-lint:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.result.outputs.status }}
    steps:
    - uses: actions/checkout@v4

    - name: Cache Mint packages
      uses: actions/cache@v4
      id: cache-mint-packages
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    
    - name: Install Mint
      run: brew install mint
    
    - name: Run SwiftFormat
      run: mint run swiftformat .

    - name: Run SwiftLint
      run: mint run swiftlint --strict

    - name: Check for changes
      id: check
      run: |
        git diff --exit-code && echo "FORMAT_OK=true" >> $GITHUB_ENV || echo "FORMAT_OK=false" >> $GITHUB_ENV
        
    - name: Set result
      id: result
      run: |
        if [ "$FORMAT_OK" = "true" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "コードフォーマットの問題が見つかりました"
          echo "status=failure" >> $GITHUB_OUTPUT
        fi 