name: Code Quality

on:
  workflow_call:
    outputs:
      result:
        description: "Check Result"
        value: ${{ jobs.format-and-lint.outputs.result }}

jobs:
  format-and-lint:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ job.status }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Mint
      run: brew install mint

    - name: Cache Mint packages
      uses: actions/cache@v4
      id: cache-mint-packages
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Bootstrap Mint packages
      run: mint bootstrap

    - name: Run SwiftFormat
      run: mint run swiftformat .

    - name: Run SwiftLint
      run: mint run swiftlint --strict

    - name: Check for formatting changes
      run: git diff --exit-code 