name: Swift Package Tests 

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result" 
        value: ${{ jobs.test-package.outputs.result }}

jobs:
  test-package:
    runs-on: macos-latest
    outputs:
      result: ${{ steps.run_tests.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode 
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Run Tests
        id: run_tests
        run: swift test 