name: Run Tests

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result"
        value: ${{ jobs.report-status.outputs.test_result }}

jobs:
  unit-test:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.unit_tests.outcome }}
    steps:
    - uses: actions/checkout@v4

    - name: Cache Mint packages
      uses: actions/cache@v4
      id: cache-mint-packages
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Install Mint
      run: brew install mint
      
    - name: Generate Xcode Project
      run: mint run xcodegen generate

    - name: Create Test Output Directories
      run: mkdir -p ci-outputs/test-results/unit
        
    - name: Make find-simulator script executable
      run: chmod +x .github/scripts/find-simulator.sh

    - name: Select Simulator
      id: select_simulator
      run: |
        SIMULATOR_ID=$(./.github/scripts/find-simulator.sh)
        echo "シミュレータ ID ($SIMULATOR_ID) が選択されました"
        echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_OUTPUT

    - name: Run Unit Tests
      id: unit_tests
      env:
        TZ: Asia/Tokyo
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用してユニットテストを実行します"
        xcodebuild test \
          -project "SampleApp.xcodeproj" \
          -scheme "SampleApp" \
          -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -configuration Debug \
          -only-testing:ScaryCatScreeningKitTests \
          CODE_SIGNING_ALLOWED=NO \
          -resultBundlePath ./ci-outputs/test-results/unit/TestResults.xcresult \
          | xcbeautify --report junit --report-path ./ci-outputs/test-results/unit/junit.xml
            
        ls -la ./ci-outputs/test-results/unit/
      continue-on-error: true

    - name: Verify Unit Test Results
      if: steps.unit_tests.outcome != 'success'
      run: |
        echo "❌ Error: Unit tests failed or did not produce results."
        RESULT_BUNDLE_PATH="./ci-outputs/test-results/unit/TestResults.xcresult"
        if [ ! -d "$RESULT_BUNDLE_PATH" ]; then
          echo "Result bundle not found at $RESULT_BUNDLE_PATH"
        fi

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results-${{ github.run_id }}
        path: ci-outputs/test-results/unit
        retention-days: 7

  report-status:
    needs: [unit-test]
    runs-on: ubuntu-latest
    if: always()
    outputs:
      test_result: ${{ steps.set_status.outputs.result }}
    steps:
      - name: Check test job outcomes and set final status
        id: set_status
        run: |
          echo "Unit Test job outcome: ${{ needs.unit-test.result }}"
          if [[ "${{ needs.unit-test.result }}" == "success" ]]; then
            echo "Unit test job succeeded."
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "Unit test job failed or was skipped."
            echo "result=failure" >> $GITHUB_OUTPUT
          fi 