name: Test Reporter

on:
  workflow_call:
    inputs:
      pull_request_number:
        description: 'Pull Request number'
        required: true
        type: number

permissions:
  checks: write         
  actions: read          
  pull-requests: write  

jobs:
  report: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create download directory
        run: mkdir -p ./ci-outputs/test-results

      - name: Download UI Test results artifact
        uses: actions/download-artifact@v4
        with:
          name: ui-test-results-${{ github.run_id }}
          path: ./ci-outputs/test-results/ui
          
      - name: Download Package Test results artifact
        uses: actions/download-artifact@v4
        with:
          name: package-test-results-${{ github.run_id }}
          path: ./ci-outputs/test-results/package

      - name: Publish Test Report as Check
        uses: mikepenz/action-junit-report@v4
        if: ${{ hashFiles('./ci-outputs/test-results/ui/junit.xml') != '' || hashFiles('./ci-outputs/test-results/package/results.xml') != '' }}
        with:
          report_paths: './ci-outputs/test-results/ui/junit.xml,./ci-outputs/test-results/package/results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: false
          require_tests: false
          check_name: 'Test Suite Results'

      - name: Create or Update PR Comment
        if: ${{ hashFiles('./ci-outputs/test-results/**/*.xml') != '' || hashFiles('./ci-outputs/test-results/package/results.xml') != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ inputs.pull_request_number }};
            if (!prNumber) {
              console.error('Could not extract pull request number.');
              return;
            }

            const { owner, repo } = context.repo;

            const commentMarker = '<!-- test-report -->';
            let commentBody = `${commentMarker}\n\n## Test Summary\n\n`;
            const fs = require('fs');

            // Test Results Summary
            const uiTestFile = './ci-outputs/test-results/ui/junit.xml';
            const packageTestFile = './ci-outputs/test-results/package/results.xml';
            if (fs.existsSync(uiTestFile) || fs.existsSync(packageTestFile)) {
               commentBody += `✅ Test Results: Available in Checks tab.\n`;
            } else {
               commentBody += `ℹ️ Test Results: No JUnit reports found.\n`;
            }

            // 既存コメントの検索・更新 or 新規作成
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: prNumber });
            const existingComment = comments.find(c => c.user.login === 'github-actions[bot]' && c.body.includes(commentMarker));

            if (existingComment) {
              console.log(`Updating comment ${existingComment.id} on PR #${prNumber}`);
              await github.rest.issues.updateComment({ owner, repo, comment_id: existingComment.id, body: commentBody });
            } else {
              console.log(`Creating new comment on PR #${prNumber}`);
              await github.rest.issues.createComment({ owner, repo, issue_number: prNumber, body: commentBody });
            }